Feature/skeleton
KtuFarm/Backend pull request #2
Opened 2021-03-09 21:45 UTC by wizacass

Setup initial API skeleton for further development

2021-03-09 22:57 UTC, Zablas requested changes
New line in Backend/appsettings.json is missing :)

2021-03-11 12:26 UTC, wizacass commented
> 
> 
> New line in Backend/appsettings.json is missing :)

Auto-formatting issues. Fixed.

2021-03-11 13:24 UTC, lukasrakauskas approved these changes

2021-03-11 13:26 UTC, Zablas approved these changes
Big Pog

2021-03-11 13:26 UTC, merged